### ISSUE TITLE
Address code quality in server files

### ISSUE THREAD

**Issue by nelsonw2014** [kochman/hotshots#16]
https://github.com/kochman/hotshots/pull/11#discussion_r169527621
https://github.com/kochman/hotshots/pull/11#discussion_r169527857
https://github.com/kochman/hotshots/pull/11#discussion_r169527969
https://github.com/kochman/hotshots/pull/11#discussion_r169528948
https://github.com/kochman/hotshots/pull/11#discussion_r169529496

Also consider creating post quick and create job system, as image processing times is upwards of 500ms

**Comment by kochman** [comment]
Resolved with #19.
