### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by nelsonw2014** [kochman/hotshots#17]
Do we care about unit tests?

Do we care about acceptance tests?

Why or why not?

What do we need to do as a result of that decision?

**Comment by nelsonw2014** [comment]
We should answer this before the end of the sprint

**Comment by nelsonw2014** [comment]
I think we need unit tests

It's becoming difficult for me to hand test edge cases without feeling like I'm missing something

I'd appreciate it if someone else would weigh in....

**Comment by kochman** [comment]
I'm in favor of unit tests. Go's testing package is super nice. Check out https://golang.org/pkg/net/http/httptest

**Comment by nelsonw2014** [comment]
@kochman Do you have a preference for location of unit tests (own directory, beside source, etc)

**Comment by nelsonw2014** [comment]
Also question for the rest is do we want to have code coverage requirements?

**Comment by kochman** [comment]
Ideally tests for things in a certain file are right next to the source (e.g. server.go tests would go in server_test.go). And then you can just make a bunch of `TestThisThing(t *testing.T)` functions in there and `go test` will discover and execute them. We should also set up Travis to do this on pull requests.

I don't think we need strict code coverage requirements, but if something can obviously be tested then it should have tests before we merge it. Anyone else have thoughts on this?

**Comment by nelsonw2014** [comment]
I think there is value in requiring a percent coverage on new pull requests. We shouldn't have less coverage as we add, we should have more. It should be manually overridable though
