### ISSUE TITLE
Determine how to uniquely identify photos

### ISSUE THREAD

**Issue by kochman** [kochman/hotshots#2]
Pushers need to be able to know what photos haven't yet been uploaded to the server. One possible scheme:

- Concatenate photo metadata (time captured, camera model, exposure settings, filename, etc.) and hash it. This becomes the photo's identifier.

**Comment by nelsonw2014** [comment]
#3 #11 

ID will the sha1 hash of the image data, currently pending merge

**Comment by nelsonw2014** [comment]
Closing the issue because this is decided
